[package]
name = "gm_naughty"
authors = ["Earu"]
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
gmod = { version = "*", default-features = false, features = ["gmcl"] }
sysinfo = "0.14.13"
vmemory = "0.1.8"